sudo: required #is required to use docker service in travis

language: python #can be any language, just php for example

services:
  - docker # required, but travis uses older version of docker :(

script:
  - pytest

before_install:
  - chmod +x ./scripts/ecr_credentials.sh
  - ./scripts/ecr_credentials.sh

after_success:
  - docker --version  # document the version travis is using
  - pip install awscli # install aws cli w/o sudo
  - export PATH=$PATH:$HOME/.local/bin # put aws in the path
  - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 730924386278.dkr.ecr.us-east-2.amazonaws.com
  - docker build -t bss .
  - docker tag bss:latest 730924386278.dkr.ecr.us-east-2.amazonaws.com/bss:latest
  - docker push 730924386278.dkr.ecr.us-east-2.amazonaws.com/bss:latest